# Generated by Django 4.2.15 on 2024-09-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_alter_book_appointment_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_appointment',
            name='admitted',
        ),
        migrations.RemoveField(
            model_name='book_appointment',
            name='upload',
        ),
    ]
