# Generated by Django 4.2.15 on 2024-09-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_remove_book_appointment_admitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='upload_report',
            field=models.FileField(default='images', upload_to='media/'),
            preserve_default=False,
        ),
    ]
