# Generated by Django 4.2.15 on 2024-09-06 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0004_book_appointment_upload_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='upload_report',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
