# Generated by Django 4.2.15 on 2024-09-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_alter_book_appointment_upload_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='medication',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
