# Generated by Django 4.2.15 on 2024-09-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=1000)),
                ('admitted', models.CharField(max_length=100)),
            ],
        ),
    ]
