# Generated by Django 4.2.15 on 2024-09-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctor_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_medication',
            name='medication',
            field=models.CharField(default='None', max_length=20),
            preserve_default=False,
        ),
    ]
